fix problems

diff --git a/compose/production/django/entrypoint b/compose/production/django/entrypoint
--- a/compose/production/django/entrypoint
+++ b/compose/production/django/entrypoint
@@ -22,23 +22,23 @@ sys.exit(0)
 END
 }
 
-rabbitmq_ready() {
-  python <<END
-import sys
-import pika
-try:
-parameters = pika.ConnectionParameters(host="${rabbitmq_host}", port=${rabbitmq_port})
-connection = pika.BlockingConnection(parameters)
-  if connection.is_open:
-    print('OK')
-    connection.close()
-    exit(0)
-except Exception as error:
-    print('Error:', error.__class__.__name__)
-    sys.exit(-1)
-sys.exit(0)
-END
-}
+# rabbitmq_ready() {
+#   python <<END
+# import sys
+# import pika
+# try:
+#   parameters = pika.URLParameters("${RABBITMQ_URL}")
+#   connection = pika.BlockingConnection(parameters)
+#   if connection.is_open:
+#     print('OK')
+#     connection.close()
+#     exit(0)
+# except Exception as error:
+#     print('Error:', error.__class__.__name__)
+#     sys.exit(-1)
+# sys.exit(0)
+# END
+# }
 until postgres_ready; do
   echo >&2 'Waiting for PostgreSQL to become available...'
   sleep 1
@@ -46,8 +46,8 @@ done
 
 echo >&2 'PostgreSQL is available'
 
-until rabbitmq_ready; do
-  echo >&2 'Waiting for Rabbitmq  to become available...'
-  sleep 1
-done
+# until rabbitmq_ready; do
+#   echo >&2 'Waiting for Rabbitmq  to become available...'
+#   sleep 1
+# done
 exec "$@"
